const KEY='skyphreak.superrot.profile.v1';
const presets={esp32:{name:'ESP32 DevKit / WROOM-32',pins:{azStep:25,azDir:26,elStep:27,elDir:14,enable:13,elLimit:33}},cnc:{name:'ESP32 + CNC Shield adapter',pins:{azStep:25,azDir:26,elStep:27,elDir:14,enable:13,elLimit:33}},custom:{name:'Custom ESP32 wiring',pins:{azStep:25,azDir:26,elStep:27,elDir:14,enable:13,elLimit:33}}};
const base={schema:1,name:'My satellite rotator',board:'esp32',driver:'step-dir',pins:{...presets.esp32.pins},mechanics:{motorSteps:200,microsteps:8,azGearRatio:7.5,elGearRatio:4},invert:{azDirection:false,elDirection:false,enable:true,elLimit:true},limits:{azMin:-720,azMax:720,elMin:0,elMax:180}};
const clone=v=>JSON.parse(JSON.stringify(v));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fld=(l,k,v,t='number',s='1')=>`<label class="srw-field"><span>${esc(l)}</span><input data-key="${esc(k)}" type="${esc(t)}" value="${esc(v)}" step="${esc(s)}"></label>`;
const chk=(l,k,v)=>`<label class="srw-check"><input data-key="${k}" type="checkbox" ${v?'checked':''}><span>${l}</span></label>`;
function set(obj,path,value){const p=path.split('.');let o=obj;for(const k of p.slice(0,-1))o=o[k];o[p.at(-1)]=value}
function normalize(x={}){return {...clone(base),...x,pins:{...base.pins,...x?.pins},mechanics:{...base.mechanics,...x?.mechanics},invert:{...base.invert,...x?.invert},limits:{...base.limits,...x?.limits}}}
function load(){try{return normalize(JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return clone(base)}}

export function openSuperRotSetup(){
 let profile=load(),page=0;const overlay=document.createElement('div');overlay.className='srw-overlay';overlay.innerHTML='<div class="srw-dialog" role="dialog" aria-modal="true"></div>';document.body.append(overlay);const box=overlay.firstElementChild;const close=()=>overlay.remove();overlay.onmousedown=e=>{if(e.target===overlay)close()};
 function read(){box.querySelectorAll('[data-key]').forEach(i=>set(profile,i.dataset.key,i.type==='checkbox'?i.checked:i.type==='number'?Number(i.value):i.value))}
 function errors(){const e=[],ps=Object.entries(profile.pins),strapping=new Set([0,2,5,12,15]);for(const[n,p]of ps){if(!Number.isInteger(p)||p<0||p>39)e.push(`${n} must be GPIO 0-39.`);if(strapping.has(p))e.push(`GPIO ${p} (${n}) is a boot-strapping pin and is not allowed by the safe profile validator.`);if(p>=6&&p<=11)e.push(`GPIO ${p} (${n}) is reserved for flash.`);if(['azStep','azDir','elStep','elDir','enable'].includes(n)&&p>=34)e.push(`GPIO ${p} is input-only and cannot drive ${n}.`)}const seen=new Set();for(const[,p]of ps){if(seen.has(p)){e.push('GPIO assignments must be unique.');break}seen.add(p)}const m=profile.mechanics;if(m.motorSteps<=0||m.microsteps<=0||m.azGearRatio<=0||m.elGearRatio<=0)e.push('Motor steps, microsteps and gear ratios must be positive.');if(profile.limits.azMin>=profile.limits.azMax||profile.limits.elMin>=profile.limits.elMax)e.push('Each minimum limit must be below its maximum.');return e}
 function render(){const titles=['Choose hardware','Assign GPIO','Configure mechanics','Travel and direction','Review and save'];let body='';
  if(page===0)body=`<div class="srw-callout">Create a reusable hardware profile. This wizard does not change or flash your working firmware.</div>${fld('Profile name','name',profile.name,'text')}<label class="srw-field"><span>Board preset</span><select data-board>${Object.entries(presets).map(([id,b])=>`<option value="${id}" ${id===profile.board?'selected':''}>${b.name}</option>`).join('')}</select></label><div class="srw-summary"><b>Driver mode</b><span>STEP / DIR (standalone)</span><small>UART is intentionally not required.</small></div>`;
  if(page===1)body=`<div class="srw-grid">${Object.entries({azStep:'AZ STEP',azDir:'AZ DIR',elStep:'EL STEP',elDir:'EL DIR',enable:'Shared ENABLE',elLimit:'EL home switch'}).map(([k,l])=>fld(l,`pins.${k}`,profile.pins[k])).join('')}</div><div class="srw-hint">GPIO 0, 2, 5, 12 and 15 are boot-strapping pins; 6-11 are reserved for flash; 34-39 are input-only.</div>`;
  if(page===2)body=`<div class="srw-grid">${fld('Motor full steps / revolution','mechanics.motorSteps',profile.mechanics.motorSteps)}${fld('Driver microsteps','mechanics.microsteps',profile.mechanics.microsteps)}${fld('AZ gear ratio','mechanics.azGearRatio',profile.mechanics.azGearRatio,'number','0.001')}${fld('EL gear ratio','mechanics.elGearRatio',profile.mechanics.elGearRatio,'number','0.001')}</div><div class="srw-summary"><b>Calculated resolution</b><span>AZ ${(360/(profile.mechanics.motorSteps*profile.mechanics.microsteps*profile.mechanics.azGearRatio)).toFixed(5)} deg/step</span><span>EL ${(360/(profile.mechanics.motorSteps*profile.mechanics.microsteps*profile.mechanics.elGearRatio)).toFixed(5)} deg/step</span></div>`;
  if(page===3)body=`<div class="srw-grid">${fld('AZ minimum (deg)','limits.azMin',profile.limits.azMin)}${fld('AZ maximum (deg)','limits.azMax',profile.limits.azMax)}${fld('EL minimum (deg)','limits.elMin',profile.limits.elMin)}${fld('EL maximum (deg)','limits.elMax',profile.limits.elMax)}</div><div class="srw-checks">${chk('Invert AZ direction','invert.azDirection',profile.invert.azDirection)}${chk('Invert EL direction','invert.elDirection',profile.invert.elDirection)}${chk('ENABLE is active-low','invert.enable',profile.invert.enable)}${chk('EL switch is active-low','invert.elLimit',profile.invert.elLimit)}</div>`;
  if(page===4){const es=errors();body=`${es.length?`<div class="srw-errors">${es.map(x=>`<div>${esc(x)}</div>`).join('')}</div>`:'<div class="srw-good">Profile is internally consistent and ready to save.</div>'}<pre class="srw-json">${esc(JSON.stringify(profile,null,2))}</pre><div class="srw-actions"><button class="btn" data-export>Export JSON</button><button class="btn" data-import>Import JSON</button><input data-file type="file" accept="application/json,.json" hidden></div><div data-flasher><div class="srw-callout">Checking local firmware assets and USB flasher...</div></div>`}
  box.innerHTML=`<header><div><small>SUPERROT BUILDER</small><h2>${titles[page]}</h2></div><button class="srw-close">&times;</button></header><div class="srw-progress">${titles.map((_,i)=>`<i class="${i<=page?'on':''}"></i>`).join('')}</div><main>${body}</main><footer><button class="btn" data-back ${page===0?'disabled':''}>Back</button><span>Step ${page+1} of 5</span>${page<4?'<button class="btn primary" data-next>Continue</button>':'<button class="btn primary" data-save>Save profile</button>'}</footer>`;
  box.querySelector('.srw-close').onclick=close;box.querySelector('[data-back]').onclick=()=>{read();page--;render()};box.querySelector('[data-next]')?.addEventListener('click',()=>{read();page++;render()});box.querySelector('[data-save]')?.addEventListener('click',()=>{if(errors().length)return render();localStorage.setItem(KEY,JSON.stringify(profile));close()});box.querySelector('[data-board]')?.addEventListener('change',e=>{profile.board=e.target.value;profile.pins={...presets[e.target.value].pins}});
  box.querySelector('[data-export]')?.addEventListener('click',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(profile,null,2)],{type:'application/json'}));a.download='superrot-profile.json';a.click();URL.revokeObjectURL(a.href)});const f=box.querySelector('[data-file]');box.querySelector('[data-import]')?.addEventListener('click',()=>f.click());f?.addEventListener('change',async()=>{try{profile=normalize(JSON.parse(await f.files[0].text()));localStorage.setItem(KEY,JSON.stringify(profile));render()}catch{alert('Invalid SuperRot profile JSON.')}});if(page===4)renderFlasher()
 }
 async function renderFlasher(){const host=box.querySelector('[data-flasher]');if(!host)return;const api=window.pyro?.flasher;if(!api?.availability||!api?.listPorts||!api?.flash){host.innerHTML='<div class="srw-callout">Firmware flashing is unavailable in this build. You can still save and export the profile.</div>';return}try{const available=await api.availability();if(!available?.ok){host.innerHTML=`<div class="srw-callout">Firmware flashing unavailable: ${esc(available?.error||'firmware assets are not installed')}.</div>`;return}const portsResult=await api.listPorts();const ports=portsResult?.ports||[];if(!portsResult?.ok||!ports.length){host.innerHTML='<div class="srw-callout">Firmware assets are ready, but no USB serial device was found. Connect the ESP32 and reopen this step.</div>';return}host.innerHTML=`<div class="srw-summary"><b>SuperRot firmware ${esc(available.firmwareVersion||'')}</b><span>${esc(available.chip||'ESP32')}</span></div><label class="srw-field"><span>USB port</span><select data-flash-port>${ports.map(p=>`<option value="${esc(p.path)}">${esc(p.label||p.path)}</option>`).join('')}</select></label><button class="btn primary" data-flash style="margin-top:12px">Flash firmware</button><div class="srw-hint" data-flash-status>This writes the bundled universal firmware. It does not yet send this hardware profile.</div>`;host.querySelector('[data-flash]').onclick=async()=>{const port=host.querySelector('[data-flash-port]').value;if(!confirm(`Flash SuperRot firmware to ${port}? This replaces the application currently on that ESP32.`))return;const button=host.querySelector('[data-flash]'),status=host.querySelector('[data-flash-status]');button.disabled=true;status.textContent='Flashing... Do not disconnect USB or power.';const result=await api.flash(port);status.textContent=result?.ok?'Firmware flashed successfully.':`Flash failed: ${result?.error||'unknown error'}`;button.disabled=false}}catch(error){host.innerHTML=`<div class="srw-callout">Could not inspect the local flasher: ${esc(error.message)}</div>`}}
 render();
}
